name: ci

on:
  push:
    branches:
      - next
  pull_request:
    branches:
      - next

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build
